table dim_desconto
	lineageTag: fddf2728-d444-4fde-b532-618093fe8a03

	column desconto_sk
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: fe1d3f27-6eb1-4435-84d2-6581e2fdcde4
		summarizeBy: none
		sourceColumn: desconto_sk

		annotation SummarizationSetBy = Automatic

	column faixa_desconto
		dataType: string
		lineageTag: 07d3163f-4799-4f76-984c-883c04c8af62
		summarizeBy: none
		sourceColumn: faixa_desconto

		annotation SummarizationSetBy = Automatic

	column percentual_minimo
		dataType: double
		formatString: 0.00%
		lineageTag: 36bed0ad-ccd6-46f7-978c-5ad9e0e18d77
		summarizeBy: none
		sourceColumn: percentual_minimo

		annotation SummarizationSetBy = Automatic

	column percentual_maximo
		dataType: double
		formatString: 0.00%
		lineageTag: 763c9779-8b95-4a22-97dd-607972ad6457
		summarizeBy: none
		sourceColumn: percentual_maximo

		annotation SummarizationSetBy = Automatic

	partition dim_desconto = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents(#"Caminho Base" & "\data\03_gold\dim_desconto.csv"),[Delimiter=",", Columns=4, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    Cabecalhos = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    Tipos = Table.TransformColumnTypes(Cabecalhos,{{"desconto_sk", Int64.Type}, {"faixa_desconto", type text}, {"percentual_minimo", type number}, {"percentual_maximo", type number}})
				in
				    Tipos

	annotation PBI_ResultType = Table

