table dim_tempo
	lineageTag: 776c9d32-6ec9-4e0c-be3d-25e6e513d1fb
	dataCategory: Time

	column tempo_sk
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 6c7d65a0-de92-4703-b64a-520bccd92c17
		summarizeBy: none
		sourceColumn: tempo_sk

		annotation SummarizationSetBy = Automatic

	column data_completa
		dataType: dateTime
		formatString: Long Date
		lineageTag: 17aaaf15-642e-4ece-879b-b06ff1a401c6
		summarizeBy: none
		sourceColumn: data_completa

		variation Variation
			isDefault
			relationship: 058fa293-96cc-4c42-90ba-6da2ed46ce96
			defaultHierarchy: LocalDateTable_97173e70-0320-4ec5-a7f1-cb66518ec2f1.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ano
		dataType: int64
		formatString: 0
		lineageTag: d55c6d6a-6e6a-4504-b539-9e42813de76a
		summarizeBy: sum
		sourceColumn: ano

		annotation SummarizationSetBy = Automatic

	column mes
		dataType: int64
		formatString: 0
		lineageTag: 98f81fbc-f87b-48f2-aa9f-3908b0b97060
		summarizeBy: sum
		sourceColumn: mes

		annotation SummarizationSetBy = Automatic

	column dia
		dataType: int64
		formatString: 0
		lineageTag: cbdf4554-3c34-4a18-8bce-a513ba937fcd
		summarizeBy: sum
		sourceColumn: dia

		annotation SummarizationSetBy = Automatic

	column dia_semana
		dataType: string
		lineageTag: 022b1355-9a76-48fc-945b-329001db8e10
		summarizeBy: none
		sourceColumn: dia_semana

		annotation SummarizationSetBy = Automatic

	column trimestre
		dataType: int64
		formatString: 0
		lineageTag: 7db209e8-1fcf-4ad4-97f0-b61e954a7387
		summarizeBy: sum
		sourceColumn: trimestre

		annotation SummarizationSetBy = Automatic

	column trimestre_fiscal
		dataType: int64
		formatString: 0
		lineageTag: 92b7606a-a958-4dea-8ba3-d203fb1f9604
		summarizeBy: sum
		sourceColumn: trimestre_fiscal

		annotation SummarizationSetBy = Automatic

	column eh_fim_mes
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 9944c4c0-c8aa-43d7-80ae-cbbc404736d8
		summarizeBy: none
		sourceColumn: eh_fim_mes

		annotation SummarizationSetBy = Automatic

	column eh_fim_trimestre
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: c2d82797-b58a-4ba9-a573-e3bcd790c16c
		summarizeBy: none
		sourceColumn: eh_fim_trimestre

		annotation SummarizationSetBy = Automatic

	column eh_fim_ano
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 05ca827c-c6ca-4c44-9a3b-72e4481ff4d2
		summarizeBy: none
		sourceColumn: eh_fim_ano

		annotation SummarizationSetBy = Automatic

	column eh_feriado_bancario
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 32474d69-e70e-44ef-b21a-5b9dbfc4f1fd
		summarizeBy: none
		sourceColumn: eh_feriado_bancario

		annotation SummarizationSetBy = Automatic

	partition dim_tempo = m
		mode: import
		source =
				let
				    DataMin = #date(2013, 1, 1),
				    DataMax = #date(2014, 12, 31),
				    Duracao = Duration.Days(DataMax - DataMin) + 1,
				    ListaDatas = List.Dates(DataMin, Duracao, #duration(1,0,0,0)),
				    TabelaDatas = Table.FromList(ListaDatas, Splitter.SplitByNothing(), {"data_completa"}, null, ExtraValues.Error),
				    FormatarTipo = Table.TransformColumnTypes(TabelaDatas,{{"data_completa", type date}}),
				    AddAno = Table.AddColumn(FormatarTipo, "ano", each Date.Year([data_completa]), Int64.Type),
				    AddMes = Table.AddColumn(AddAno, "mes", each Date.Month([data_completa]), Int64.Type),
				    AddDia = Table.AddColumn(AddMes, "dia", each Date.Day([data_completa]), Int64.Type),
				    AddTrimestre = Table.AddColumn(AddDia, "trimestre", each Date.QuarterOfYear([data_completa]), Int64.Type),
				    AddTempoSk = Table.AddColumn(AddTrimestre, "tempo_sk", each Date.Year([data_completa])*10000 + Date.Month([data_completa])*100 + Date.Day([data_completa]), Int64.Type)
				in
				    AddTempoSk

	annotation PBI_ResultType = Table

