table dim_desconto
	lineageTag: fddf2728-d444-4fde-b532-618093fe8a03

	column desconto_sk
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: fe1d3f27-6eb1-4435-84d2-6581e2fdcde4
		summarizeBy: sum
		sourceColumn: desconto_sk

		annotation SummarizationSetBy = Automatic

	column faixa_desconto
		dataType: string
		lineageTag: 07d3163f-4799-4f76-984c-883c04c8af62
		summarizeBy: none
		sourceColumn: faixa_desconto

		annotation SummarizationSetBy = Automatic

	column percentual_min
		dataType: int64
		formatString: 0
		lineageTag: 36bed0ad-ccd6-46f7-978c-5ad9e0e18d77
		summarizeBy: sum
		sourceColumn: percentual_min

		annotation SummarizationSetBy = Automatic

	column percentual_max
		dataType: int64
		formatString: 0
		lineageTag: 763c9779-8b95-4a22-97dd-607972ad6457
		summarizeBy: sum
		sourceColumn: percentual_max

		annotation SummarizationSetBy = Automatic

	partition dim_desconto = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents("C:\Users\Claiton\Documents\GitHub\Conjunto de Dados Financeiros da Empresa\data\03_gold\dim_desconto.csv"),[Delimiter=",", Columns=4, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"desconto_sk", Int64.Type}, {"faixa_desconto", type text}, {"percentual_min", Int64.Type}, {"percentual_max", Int64.Type}})
				in
				    #"Tipo Alterado"

	annotation PBI_ResultType = Table

