table dim_geografia
	lineageTag: b5815784-f2cc-4036-b37f-4a3dc7d8962a

	column geografia_sk
		dataType: int64
		formatString: 0
		lineageTag: 5d042100-27db-4be9-ad11-90b8b40e7a18
		summarizeBy: none
		sourceColumn: geografia_sk

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column pais
		dataType: string
		lineageTag: d1e9b8a3-b4ef-435a-b921-bce3ba32d8ee
		summarizeBy: none
		sourceColumn: pais

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column continente
		dataType: string
		lineageTag: 166f94cf-e959-476a-83d6-f365b7b884b0
		summarizeBy: none
		sourceColumn: continente

		annotation SummarizationSetBy = Automatic

	column regiao
		dataType: string
		lineageTag: 3aa79402-0c12-45c6-a7f4-a57ac12d95ab
		summarizeBy: none
		sourceColumn: regiao

		annotation SummarizationSetBy = Automatic

	partition dim_geografia = m
		mode: import
		source = ```
				let
				    Fonte = Csv.Document(File.Contents("C:\Users\Claiton\Documents\GitHub\Conjunto de Dados Financeiros da Empresa\data\03_gold\dim_geografia.csv"),[Delimiter=",", Columns=4, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    Cabecalhos = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    Renomear = Table.RenameColumns(Cabecalhos,{{"pais", "País"}}),
				    Traduzir = Table.TransformColumns(Renomear, {{"País", each 
				        if _ = "United States of America" then "Estados Unidos" else
				        if _ = "France" then "França" else
				        if _ = "Germany" then "Alemanha" else
				        if _ = "Mexico" then "México" else
				        if _ = "Canada" then "Canadá" else _, type text
				    }})
				in
				    Traduzir
				```

	annotation PBI_ResultType = Table

