table fato_financeiro
	lineageTag: 6b216d53-2ee0-4459-9b22-5d6758b272fb

	column fato_financeiro_sk
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 550fcb29-0e44-4a43-9874-828201bb5024
		summarizeBy: none
		sourceColumn: fato_financeiro_sk

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column produto_sk
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 1b24fa22-33cd-430e-8306-82c347e780fa
		summarizeBy: none
		sourceColumn: produto_sk

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column geografia_sk
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: ad189bbc-1155-453b-9852-a84176b23584
		summarizeBy: none
		sourceColumn: geografia_sk

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column segmento_sk
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: d9310004-b068-4c52-ba06-062e36893e16
		summarizeBy: none
		sourceColumn: segmento_sk

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column desconto_sk
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 2337a036-2e93-464c-b860-3647c7e10cc7
		summarizeBy: none
		sourceColumn: desconto_sk

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column tempo_sk
		dataType: int64
		formatString: 0
		lineageTag: b929db35-6c82-4b6f-ba26-8d679c0efba7
		summarizeBy: none
		sourceColumn: tempo_sk

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Unidades Vendidas'
		dataType: double
		formatString: 0
		lineageTag: 06023d4f-6f14-42a4-ba52-add158950d9f
		summarizeBy: sum
		sourceColumn: unidades_vendidas

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Receita Líquida'
		dataType: decimal
		formatString: R$ #,0.00
		lineageTag: c0ff3538-2f0a-4e86-8791-66cbddc20cf0
		summarizeBy: sum
		sourceColumn: receita_liquida

		annotation SummarizationSetBy = Automatic

	column 'Custo (CPV)'
		dataType: decimal
		formatString: R$ #,0.00
		lineageTag: c838ec70-0330-4f44-a171-d1b8ea7b4505
		summarizeBy: sum
		sourceColumn: custo_produtos_vendidos

		annotation SummarizationSetBy = Automatic

	column Lucro
		dataType: decimal
		formatString: 0
		lineageTag: 54227eab-a06f-4091-92a9-746a6d4fe16f
		summarizeBy: sum
		sourceColumn: lucro

		annotation SummarizationSetBy = Automatic

	partition fato_financeiro = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents(#"Caminho Base" & "\data\03_gold\fato_financeiro.csv"),[Delimiter=",", Columns=10, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    Cabecalhos = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    Tipos = Table.TransformColumnTypes(Cabecalhos,{{"fato_financeiro_sk", Int64.Type}, {"produto_sk", Int64.Type}, {"geografia_sk", Int64.Type}, {"segmento_sk", Int64.Type}, {"desconto_sk", Int64.Type}, {"tempo_sk", Int64.Type}, {"unidades_vendidas", type number}, {"receita_liquida", Currency.Type}, {"custo_produtos_vendidos", Currency.Type}, {"lucro", Currency.Type}})
				in
				    Tipos

	annotation PBI_ResultType = Table

